### ISSUE TITLE
MYSQL issue connection

### ISSUE THREAD

**Issue by Talesu** [thedutchruben/TDRPlaytime#18]
https://paste.helpch.at/ekudejebez.md
That's the pastebin for the MYSQL Error, this happens when the player gets "disconnected" but isn't disconnected.
A small break in the connection.

**Comment by WongIong** [comment]
have this too
i edit the database.yml
added a value "autoreconnect: true"

**Comment by thedutchruben** [comment]
Hey,
The database now reconnects automatically.
  You can download the new version here: https://www.spigotmc.org/resources/tdrplaytime-rewards-mysql.47894/update?update=422840
