### ISSUE TITLE
Migration not working?

### ISSUE THREAD

**Issue by troke12** [thedutchruben/TDRPlaytime#20]
as you can see on the video below, theres no column named `playtime` after migrating, also i'm already restart them for 2 times and still theres no playtime column in my database

https://user-images.githubusercontent.com/10250068/135412604-a8febe49-88f4-47a5-819d-c65b041110c8.mp4

**Comment by thedutchruben** [comment]
In the config database is still on yaml that needs to be changed to mysql

**Comment by troke12** [comment]
already changed, before i start the migrate command i change that in database.yml, as you can see on the video that i exposed my database.yml but dont worry the password already changed

**Comment by srnyx** [comment]
Not working for me either
