### ISSUE TITLE
Edit or remove repeatingmilestone  ?

### ISSUE THREAD

**Issue by nnnarvaez** [thedutchruben/TDRPlaytime#37]
The milestones creat a yml database in the server but not a repeatingmilestone database.
I can't find a command to edit a repeating milestone if i make a addcommand mistake for example

**Comment by thedutchruben** [comment]
Hey,

In the next update it's possible to remove milestones , updating them will come later

**Comment by thedutchruben** [comment]
This is fixed by the latest update https://www.spigotmc.org/resources/tdr-playtime-rewards-mysql.47894/update?update=466897
